### PR TITLE
Avoid mixed content link traversal when using the query in the browser via https

### PR DESCRIPTION
**Pull request by Maximvdw**
**Problem**
When using the link traversal in the browser via insecure http - no issues exist. When using https you will get [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) errors when the engine tries to fetch an http link.

Eventually this could lead to the query not functioning as expected with many links not being visited
Something that can easily be tested here: https://comunica.github.io/comunica-feature-link-traversal-web-clients/builds/default

**Proposed solution**
1. Check if we are using a browser (`globalThis.window` not being undefined)
*`globalThis` is used for compatibility with jest and NodeJS as well as the browser*
3. Check if the location URL is present (`globalThis.window.location` not being undefined)
4. Check if the location URL uses `https:`
*there is a window.isSecureContext but it [might not be supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext)*
6. If yes, check if the `fileLink.url` uses `http:`
7. If yes, replace it to `https:` to avoid mixed content errors

It could be that the remote server does not offer the `fileLink.url` in https - but it is a better attempt to try and visit it via https than to let the browser throw an error.
Example: http://qudt.org/vocab/unit/M  VS https://qudt.org/vocab/unit/M
The latter will not work - but on HTTPS, the first one won't work either.

**Current workarounds**
Current workarounds would be to use an HTTPS proxy that does not care about mixed content e.g. https://proxy.linkeddatafragments.org/

**Changes**
- Proposed solution (see above)
- Added jest config option for the window object
*Not absolutely required - but added for other future tests*
- Added unit test for replacing `http` links to `https` when the browser is using `https:`
- Added unit test for NOT replacing `http` links when the browser is not using `https:`

The following commit has been tested with NodeJS and in the browser where the issue is present.

### CODE REVIEW

**Comment by Maximvdw** [comment]
The current issue is that in the case of proxies - it will still try to change it to https. Will see what can be done about that (i.e. disable the fix for proxies)

Example:
https://proxy.linkeddatafragments.org/http://qudt.org/vocab/unit/M
works and will not throw a mixed-content error

https://proxy.linkeddatafragments.org/https://qudt.org/vocab/unit/M
does not work

**Comment by rubensworks** [comment]
Thanks for the PR @Maximvdw!

It's unfortunate that a fix like this is needed, but the mixed content errors are out of our control, so I agree that the workaround is valid.

However, we should be aware that strictly speaking a http resource is not the same as a https resource (it _may_ refer to a different page). So I would suggest adding an option to the actor that allows this behaviour to be disabled, just in case people run into problems because of it. E.g. something like `liftToHttps`, that defaults to `true`. (can be done like this: https://github.com/comunica/comunica/blob/master/packages/actor-rdf-resolve-quad-pattern-federated/lib/ActorRdfResolveQuadPatternFederated.ts#L50-L55)

**Comment by Maximvdw** [comment]
I will add the option and check the ci errors later today

**Comment by rubensworks** [comment]
Excellent work @Maximvdw, thanks for this!

And indeed, `upgradeInsecureRequests` is much clearer than what I suggested 😅 

Publishing `alpha.4.0` now...

**Pull request merged**
